language: python 
python: 
- "3.6"
env: 
- DJANGO=2.0 DB=postgres
addons:
  postgresql: "9.6"
before_install: 
- cd decide
- psql -c "CREATE USER decide WITH PASSWORD 'decide';" -U postgres
- psql -c "ALTER USER decide superuser;" -U postgres
install: 
- pip install -r ../requirements.txt
script: 
- python3 manage.py test
deploy:
  provider: heroku
  api_key: af4c448b-fe95-4b0f-972c-cd8812fbd14b
  app:
    master: decideeuropacenso
